### PR TITLE
Disposed Runner when unloading Tests so the Agent process terminates

### PR DESCRIPTION
**Pull request by JeffKryzer**
I'm pretty sure this issue is what is being referred to in issue #241.

### CODE REVIEW

**Comment by CharliePoole** [comment]
Were you able to confirm the issue with either the current master or the beta release?

**Comment by JeffKryzer** [comment]
First repro-ed it when downloading the beta release.  Later pulled down the master source code and confirmed it after compiling.

**Comment by CharliePoole** [comment]
We once had some ability to re-use agents, depending on the nature of the change. For example, changing the framework or x86 setting requires a new agent but changing reload-on-run would not.

Somewhere in the depths of time, I think this was lost. I want to check to see if it can be put back in a timely fashion. If not, then I think we should go with your solution for the 1.0 release.

This question may also apply to one or two others of your issues, IIRC.

**Comment by CharliePoole** [comment]
Hey! Thanks for your contribution!

**Comment by JeffKryzer** [comment]
You're welcome, sir.  I'm on a project where we just upgraded from NUnit 2.6 to 3.0 and suddenly we didn't have a GUI to use.  Needed to get it up and running to match functionality from NUnit GUI 2.x, and as you can probably guess, we're running our tests as x86 which immediately failed.  IMO, running the tests inside of Visual Studio just sucks,  So much recompiling just to run a test!

**Comment by CharliePoole** [comment]
The general idea is that the 1.0 release should provide equivalent functionality to the V2 GUI. In a pinch, I may release 1.0 and push anything that's less used to 1.1.

Feel free to write issues where you see missing functionality, if there isn't already one.

**Pull request merged**
