### PR TITLE
New Icons for TestCentric

### LINKED ISSUE #8: Icon and Logo for TestCentric
Currently using NUnit's but we should have our own.

### PR DESCRIPTION
**Pull request by CharliePoole**
Fixes #8

### CODE REVIEW

**Comment by CharliePoole** [comment]
I'm not 100% happy with the icons. At 32x32, it's hard to see the "T" - at least for my eyes. However, it gets rid of using the NUnit icon and opens the door to getting the release out, so I'm merging this and we can make incremental improvements later if we like.

**Comment by AlexejHirsch** [comment]
I have a suggestion regarding the new icon. Maybe you like my quick and dirty draft. See attached files:
testcentric_256
testcentric_128
testcentric_32
testcentric_16

**Comment by CharliePoole** [comment]
@AlexejHirsch Thanks for the icons. Since I had already merged, I'm holding on to these for a possible future update. I like the bigger "T" especially in the smallest size.

**Comment by AlexejHirsch** [comment]
@CharliePoole I have created a better version of the icons. Especialy the smallest icon looks 
a little clearer than the previous one.
testcentric_256
testcentric_128
testcentric_32
testcentric_16

**Comment by CharliePoole** [comment]
@TestCentric/gui-team What do you think of @AlexejHirsch 's version as opposed to the one merged?

**Comment by immeraufdemhund** [comment]
yeah I like @AlexejHirsch 's icons more. Everything pops better at lower res and looks great at a higher res

**Comment by CharliePoole** [comment]
Thoughts...

Would it be better for these icons to forget about the letter C and just complete the circle?

What about square or angled end caps on the T?

Should we go back to the NUnit design, just substituting either "T" or "TC" for the "n"?

I'll do some samples of what I mean when I get a chance.

**Comment by CharliePoole** [comment]
I'm going ahead with the release and we'll continue to improve the icon's using @AlexejHirsch 's work in the coming months. My window of opportunity to focus on the release is coming to an end as I'll be travelling quite a bit over the next three weeks and I'd really like to see 1.0 out there!

**Pull request merged**
