### PR TITLE
Fix reload on change take2

### LINKED ISSUE #18: Reload on Change not working
We should set up file watchers and reload the tests if needed. Ideally, only reload the assembly that changed if multiple assemblies are open.

### PR DESCRIPTION
**Pull request by drSte**
fixes #18

### CODE REVIEW

**Comment by CharliePoole** [comment]
Changes to `LongRunningOperationDisplay` and `TestTreeView` make sense in terms of avoiding errors due to ues of the wrong thread. But they also look like they are unrelated to the particular issue. To the extent possible, I see us working toward minimal diffs that do one simple thing so we can rapidly merge them.

There's no need to change this now... just note for the future. Hint: if it seems like too much overhead to do a separate PR and merge for a small change, we need to learn how to eliminate the overhead. :smiley_cat:

**Comment by drSte** [comment]
the changes are needed, the port won't work without

**Comment by CharliePoole** [comment]
Well, OK then. :-)

**Comment by drSte** [comment]
@CharliePoole, as discussed with @mikkelbu I am pushing only my changes in master

**Comment by CharliePoole** [comment]
It looks like something when wrong in your merge. In this situation, I'd merge your changes into master via rebase rather than merging master into your branch. That's because the changes in master are much more extensive. Alternatively, just create a new branch from master and re-apply your changes manually.

Do you keep a local master? That's generally the best way to work, creating each new branch from the local master, which you periodically update.

**Comment by drSte** [comment]
@CharliePoole I keep a local master and I updated before creating the branch. Would it be possible for you to rebase? If not I will try to reimplement the changes on an updated master

**Comment by CharliePoole** [comment]
@drSte Not sure what you mean. The master has changed from the one on which you based your branch. Most frequently, GitHub takes care of that when it merges the PR. But when there are a lot of different changes in the same files it will often not work. In this case, the merge created by GitHub will not compile. What you would normally do is pull the latest master and then rebase your branch on top of it. Then you can resolve the conflicts with knowledge of what you are intending to change.

Assuming you are using the command-line, you would do `git pull` in your master branch followed by `git rebase master` in your working branch. There's no need to start a new branch and it's much easier to rebase a small number of changes on top of a large number rather than the reverse.

Please ask if anything isn't clear.

**Comment by CharliePoole** [comment]
Aside from my general comment about observing the settings, this looks good. If you like I can manually merge it for you manually when we are ready.

**Comment by CharliePoole** [comment]
@drSte Haven't heard from you about this for a few days. Are you still working on it?

**Comment by drSte** [comment]
Hi @CharliePoole , I will manage to restart contributing from middle of November on, sorry for the delay.
If it is not possible to wait so much time, someone else can take care of the merge

**Comment by CharliePoole** [comment]
I'm going to leave this out of the alpha2 release in that case and we can continue afterwards.

**Comment by CharliePoole** [comment]
Closing - replaced by #162

**Pull request closed without merging**
